name: markdown-link-check

on:
  push:
    branches:
      # Run on pushes to default branch
      - main
  # Run against pull requests
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
